language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install coveralls
  - pip install .
  - pip install -r requirements.txt
services:
  - mysql
env:
  - DJANGO=1.10.4 DB=mysql
before_script:
  - mysql -e 'create database YAYATA;' -u root
script:
  - coverage run --source=ninetofiver manage.py testninetofiver
after_success:
  - coveralls
